import { Injectable } from '@angular/core';
declare var CodeMirror: any;

function getWindow (): any {
    return window;
}

@Injectable()
export class CodeMirrorEditorProvider {
    constructor(){}
    languagesMetaData: any = {
        'apl': {mimes: ["text/apl"], mode: "apl"},
        "pgp": {mimes: ["application/pgp", "application/pgp-keys", "application/pgp-signature"], mode: "asciiarmor"},
        "asn.1": { mimes: ["text/x-ttcn-asn"], mode: "asn.1" },
        "asterisk": { mimes: ["text/x-asterisk"], mode: "asterisk"},
        "brainfuck": {mimes: ["text/x-brainfuck"], mode: "brainfuck"},
        'c': {mimes: ['text/x-csrc'], mode: 'clike' },
        'c++': {mimes: ['text/x-c++src'], mode: 'clike' },
        'cpp': {mimes: ['text/x-c++src'], mode: 'clike' },  
        "cobol": {mimes: ["text/x-cobol"], mode: "cobol"},
        'c#': {mimes: ['text/x-csharp'], mode: 'clike'},
        "clojure": {mimes: ["text/x-clojure"], mode: "clojure"},
        "clojurescript":  {mimes: ["text/x-clojurescript"], mode: "clojure"},
        "closure stylesheets (gss)": {mimes: ["text/x-gss"], mode: "css"},
        "cmake": {mimes: ["text/x-cmake"], mode: "cmake"},
        "coffeescript": {mimes: ["text/x-coffeescript"], mode: "coffeescript"},
        "common lisp": {mimes: ["text/x-common-lisp"], mode: "commonlisp"},
        "cypher": {mimes: ["application/x-cypher-query"], mode: "cypher"},
        'cython': { mimes: ["text/x-cython"], mode: "python"},
        "crystal": {mimes: ["text/x-crystal"], mode: "crystal"},
        'css': {mimes: ["text/css"], mode: "css" },
        "cql": {mimes: ["text/x-cassandra"], mode: "sql"},
        "d": {mimes: ["text/x-d"], mode: "d"},
        "dart": {mimes: ["application/dart", "text/x-dart"], mode: "dart"},
        "diff": {mimes: ["text/x-diff"], mode: "diff"},
        "django": {mimes: ["text/x-django"], mode: "django"},
        "dockerfile": {mimes: ["text/x-dockerfile"], mode: "dockerfile"},
        "dtd": {mimes: ["application/xml-dtd"], mode: "dtd"},
        "dylan": {mimes: ["text/x-dylan"], mode: "dylan"},
        "ebnf": {mimes: ["text/x-ebnf"], mode: "ebnf"},
        "ecl": {mimes: ["text/x-ecl"], mode: "ecl"},
        "edn": {mimes: ["application/edn"], mode: "clojure"},
        "eiffel": {mimes: ["text/x-eiffel"], mode: "eiffel"},
        "elm": {mimes: ["text/x-elm"], mode: "elm"},
        "embedded javascript": {mimes: ["application/x-ejs"], mode: "htmlembedded"},
        "embedded ruby": {mimes: ["application/x-erb"], mode: "htmlembedded"},
        "erlang": {mimes: ["text/x-erlang"], mode: "erlang"},
        "factor": {mimes: ["text/x-factor"], mode: "factor"},
        "fcl": {mimes: ["text/x-fcl"], mode: "fcl"},
        "forth": {mimes: ["text/x-forth"], mode: "forth"},
        "fortran": {mimes: ["text/x-fortran"], mode: "fortran"},
        "f#": {mimes: ["text/x-fsharp"], mode: "mllike"},
        "gas": {mimes: ["text/x-gas"], mode: "gas"},
        "gherkin": {mimes: ["text/x-feature"], mode: "gherkin"},
        "gitHub flavored markdown": {mimes:["text/x-gfm"], mode: "gfm"},
        "go": {mimes: ["text/x-go"], mode: "go"},
        "groovy": {mimes: ["text/x-groovy"], mode: "groovy"},
        "haml": {mimes: ["text/x-haml"], mode: "haml"},
        "haskell": {mimes: ["text/x-haskell"], mode: "haskell"},
        "haskell (literate)": {mimes: ["text/x-literate-haskell"], mode: "haskell-literate"},
        "haxe": {mimes: ["text/x-haxe"], mode: "haxe"},
        "hxml": {mimes: ["text/x-hxml"], mode: "haxe"},
        "asp.net": {mimes: ["application/x-aspx"], mode: "htmlembedded"},
        "html": {mimes: ["text/html"], mode: "htmlmixed"},
        "http": {mimes: ["message/http"], mode: "http"},
        "idl": {mimes: ["text/x-idl"], mode: "idl"},
        "pug": {mimes: ["text/x-pug"], mode: "pug"},
    	'java': {mimes: ['text/x-java'], mode: 'clike' },
        'java server pages': { mimes: ["application/x-jsp"], mode: "htmlembedded"},
        'javascript': { mimes: ["text/javascript", "text/ecmascript", "application/javascript", "application/x-javascript", "application/ecmascript"],  mode: "javascript"},
    	"json": {mimes: ["application/json", "application/x-json"], mode: "javascript"},
        "json-ld": {mimes: ["application/ld+json"], mode: "javascript"},
        "jsx": {mimes: ["text/jsx"], mode: "jsx"},
        "jinja2": {mimes: ["null"], mode: "jinja2"},
        "julia": {mimes: ["text/x-julia"], mode: "julia"},
        'kotlin': {mimes: ['text/x-kotlin'], mode: 'clike'},
    	'objective c': { mimes: ['text/x-objectivec'], mode: 'clike'},
        "perl": {mimes: ["text/x-perl"], mode: "perl"},
        "php": {mimes: ["application/x-httpd-php"], mode: "php"},
        "plain text": {mimes: ["text/plain"], mode: "null"},
        "plsql": {mimes: ["text/x-plsql"], mode: "sql"},
        "powershell": {mimes: ["application/x-powershell"], mode: "powershell"},
        'python': {mimes: ["text/x-python"], mode: "python"},
        "ruby": {mimes: ["text/x-ruby"], mode: "ruby"},
    	'scala': { mimes: ['text/x-scala'], mode: 'clike'},
    	'squirrel': { mimes: ['text/x-squirrel'], mode: 'clike'},
        'sass': {mimes: ["text/x-sass"], mode: "sass"},
        'swift': {mimes: ["text/x-swift"], mode: "swift"},
        "typescript": {mimes: ["application/typescript"], mode: "javascript"},
        "vb.net": {mimes: ["text/x-vb"], mode: "vb"},
        "vbscript": {mimes: ["text/vbscript"], mode: "vbscript"},
        'xml': { mimes: ["application/xml", "text/xml"], mode: "xml" },
        "xquery": {mimes: ["application/xquery"], mode: "xquery"},
        "yaml": {mimes: ["text/x-yaml", "text/yaml"], mode: "yaml"}
    }
    getLanguageMetaData(language: string) {
    	return this.languagesMetaData[language.toLowerCase()];
    }
}